In [1]:
import numpy as np
import pandas as pd
import csv




In [12]:
sim_qc_speed = [node_36, node_37, node_38, node_39, node_40, node_41, node_42, node_43]
sim_qc_subadj = np.array([[0, 1, 0, 0, 0, 0, 0, 0], # 36
                          [1, 0, 1, 0, 0, 0, 0, 0], # 37
                          [0, 1, 0, 1, 0, 0, 0, 0], # 38
                          [0, 0, 1, 0, 1, 0, 0, 0], # 39
                          [0, 0, 0, 1, 0, 1, 1, 0], # 40
                          [0, 0, 0, 0, 1, 0, 0, 0], # 41
                          [0, 0, 0, 0, 1, 0, 0, 1], # 42
                          [0, 0, 0, 0, 0, 0, 1, 0]]) # 43

print(sim_qc_subadj)

[[0 1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 0 1 0 1 0 0 0]
 [0 0 0 1 0 1 1 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 0]]


In [14]:
# with open('sim_qc_speed.csv', 'w', newline='') as csvfile:
#     csv_writer = csv.writer(csvfile)
#     for row in sim_qc_speed:
#         csv_writer.writerow(row)

# with open('sim_qc_adj.csv', 'w', newline='') as csvfile:
#     csv_writer = csv.writer(csvfile)
#     for row in sim_qc_subadj:
#         csv_writer.writerow(row)

np.save(r'C:\FILES\thesis-vsc-files\data\simulated-qc\simulated-road\sim_qc_speed.npy',sim_qc_speed)
np.save(r'C:\FILES\thesis-vsc-files\data\simulated-qc\simulated-road\sim_qc_adj.npy',sim_qc_subadj)